name: Main Workflow

on: [push, pull_request]
  
defaults:
  run: 
    shell: bash

# Jobs run in parallel by default
jobs:
  dev-build:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'feature') || endsWith(github.ref, '/develop') || startsWith(github.ref, 'refs/pull/')
    env:
      ENVIRONMENT: dev
      BRANCH: ${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.zaproxy.org'
          cmd_options: '-a'

      # - name: cache gradle packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.gradle/cache
      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      #     restore-keys: ${{ runner.os }}-gradle

      # - name: cache sonarcloud packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.sonar/cache
      #     key: ${{runner.os}}-sonar
      #     restore-keys: ${{ runner.os }}-sonar

      # - name: sonarcloud scan
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     chmod +x ./gradlew
      #     ./gradlew build jacocoTestReport sonarqube --info

      # - name: DevSkim
      #   uses: microsoft/DevSkim-Action@v1
      #   with:
      #     output-filename: devskim-results.sarif
      #     output-directory: ./

      # - name: show results
      #   run: cat ./devskim-results.sarif
